syntax = "proto3";

package minecraftai;

option java_package = "me.sand.minecraftaimod.protobuf";
option java_multiple_files = true;

message Matrix3D {
  repeated Matrix matrix = 1;
}

message Matrix4D {
  repeated Matrix3D matrix3D = 1;
}

message Matrix {
  repeated Row rows = 1;
}

message Row {
  repeated double values = 1;
}

message State {
  repeated double agentInfo = 1;
  Matrix inventory = 2;
  Matrix nearbyEntities = 3;
  Matrix3D nearbyBlocks = 4;
  Matrix4D nearbyItemDrops = 5;
  Matrix container = 6;
  double containerType = 7;
}

message Action {
  repeated float actions = 1;
}
