// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: state.proto

package me.sand.minecraftaimod.protobuf;

/**
 * Protobuf type {@code minecraftai.Action}
 */
public final class Action extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:minecraftai.Action)
    ActionOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Action.newBuilder() to construct.
  private Action(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Action() {
    actions_ = emptyFloatList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Action();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return me.sand.minecraftaimod.protobuf.StateOuterClass.internal_static_minecraftai_Action_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return me.sand.minecraftaimod.protobuf.StateOuterClass.internal_static_minecraftai_Action_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            me.sand.minecraftaimod.protobuf.Action.class, me.sand.minecraftaimod.protobuf.Action.Builder.class);
  }

  public static final int ACTIONS_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private com.google.protobuf.Internal.FloatList actions_;
  /**
   * <code>repeated float actions = 1;</code>
   * @return A list containing the actions.
   */
  @java.lang.Override
  public java.util.List<java.lang.Float>
      getActionsList() {
    return actions_;
  }
  /**
   * <code>repeated float actions = 1;</code>
   * @return The count of actions.
   */
  public int getActionsCount() {
    return actions_.size();
  }
  /**
   * <code>repeated float actions = 1;</code>
   * @param index The index of the element to return.
   * @return The actions at the given index.
   */
  public float getActions(int index) {
    return actions_.getFloat(index);
  }
  private int actionsMemoizedSerializedSize = -1;

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (getActionsList().size() > 0) {
      output.writeUInt32NoTag(10);
      output.writeUInt32NoTag(actionsMemoizedSerializedSize);
    }
    for (int i = 0; i < actions_.size(); i++) {
      output.writeFloatNoTag(actions_.getFloat(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      dataSize = 4 * getActionsList().size();
      size += dataSize;
      if (!getActionsList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      actionsMemoizedSerializedSize = dataSize;
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof me.sand.minecraftaimod.protobuf.Action)) {
      return super.equals(obj);
    }
    me.sand.minecraftaimod.protobuf.Action other = (me.sand.minecraftaimod.protobuf.Action) obj;

    if (!getActionsList()
        .equals(other.getActionsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getActionsCount() > 0) {
      hash = (37 * hash) + ACTIONS_FIELD_NUMBER;
      hash = (53 * hash) + getActionsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static me.sand.minecraftaimod.protobuf.Action parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static me.sand.minecraftaimod.protobuf.Action parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static me.sand.minecraftaimod.protobuf.Action parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static me.sand.minecraftaimod.protobuf.Action parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static me.sand.minecraftaimod.protobuf.Action parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static me.sand.minecraftaimod.protobuf.Action parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static me.sand.minecraftaimod.protobuf.Action parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static me.sand.minecraftaimod.protobuf.Action parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static me.sand.minecraftaimod.protobuf.Action parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static me.sand.minecraftaimod.protobuf.Action parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static me.sand.minecraftaimod.protobuf.Action parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static me.sand.minecraftaimod.protobuf.Action parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(me.sand.minecraftaimod.protobuf.Action prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code minecraftai.Action}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:minecraftai.Action)
      me.sand.minecraftaimod.protobuf.ActionOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return me.sand.minecraftaimod.protobuf.StateOuterClass.internal_static_minecraftai_Action_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return me.sand.minecraftaimod.protobuf.StateOuterClass.internal_static_minecraftai_Action_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              me.sand.minecraftaimod.protobuf.Action.class, me.sand.minecraftaimod.protobuf.Action.Builder.class);
    }

    // Construct using me.sand.minecraftaimod.protobuf.Action.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      actions_ = emptyFloatList();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return me.sand.minecraftaimod.protobuf.StateOuterClass.internal_static_minecraftai_Action_descriptor;
    }

    @java.lang.Override
    public me.sand.minecraftaimod.protobuf.Action getDefaultInstanceForType() {
      return me.sand.minecraftaimod.protobuf.Action.getDefaultInstance();
    }

    @java.lang.Override
    public me.sand.minecraftaimod.protobuf.Action build() {
      me.sand.minecraftaimod.protobuf.Action result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public me.sand.minecraftaimod.protobuf.Action buildPartial() {
      me.sand.minecraftaimod.protobuf.Action result = new me.sand.minecraftaimod.protobuf.Action(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(me.sand.minecraftaimod.protobuf.Action result) {
      if (((bitField0_ & 0x00000001) != 0)) {
        actions_.makeImmutable();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.actions_ = actions_;
    }

    private void buildPartial0(me.sand.minecraftaimod.protobuf.Action result) {
      int from_bitField0_ = bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof me.sand.minecraftaimod.protobuf.Action) {
        return mergeFrom((me.sand.minecraftaimod.protobuf.Action)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(me.sand.minecraftaimod.protobuf.Action other) {
      if (other == me.sand.minecraftaimod.protobuf.Action.getDefaultInstance()) return this;
      if (!other.actions_.isEmpty()) {
        if (actions_.isEmpty()) {
          actions_ = other.actions_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureActionsIsMutable();
          actions_.addAll(other.actions_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 13: {
              float v = input.readFloat();
              ensureActionsIsMutable();
              actions_.addFloat(v);
              break;
            } // case 13
            case 10: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              ensureActionsIsMutable();
              while (input.getBytesUntilLimit() > 0) {
                actions_.addFloat(input.readFloat());
              }
              input.popLimit(limit);
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.Internal.FloatList actions_ = emptyFloatList();
    private void ensureActionsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        actions_ = mutableCopy(actions_);
        bitField0_ |= 0x00000001;
      }
    }
    /**
     * <code>repeated float actions = 1;</code>
     * @return A list containing the actions.
     */
    public java.util.List<java.lang.Float>
        getActionsList() {
      return ((bitField0_ & 0x00000001) != 0) ?
               java.util.Collections.unmodifiableList(actions_) : actions_;
    }
    /**
     * <code>repeated float actions = 1;</code>
     * @return The count of actions.
     */
    public int getActionsCount() {
      return actions_.size();
    }
    /**
     * <code>repeated float actions = 1;</code>
     * @param index The index of the element to return.
     * @return The actions at the given index.
     */
    public float getActions(int index) {
      return actions_.getFloat(index);
    }
    /**
     * <code>repeated float actions = 1;</code>
     * @param index The index to set the value at.
     * @param value The actions to set.
     * @return This builder for chaining.
     */
    public Builder setActions(
        int index, float value) {
      
      ensureActionsIsMutable();
      actions_.setFloat(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated float actions = 1;</code>
     * @param value The actions to add.
     * @return This builder for chaining.
     */
    public Builder addActions(float value) {
      
      ensureActionsIsMutable();
      actions_.addFloat(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated float actions = 1;</code>
     * @param values The actions to add.
     * @return This builder for chaining.
     */
    public Builder addAllActions(
        java.lang.Iterable<? extends java.lang.Float> values) {
      ensureActionsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, actions_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated float actions = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearActions() {
      actions_ = emptyFloatList();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:minecraftai.Action)
  }

  // @@protoc_insertion_point(class_scope:minecraftai.Action)
  private static final me.sand.minecraftaimod.protobuf.Action DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new me.sand.minecraftaimod.protobuf.Action();
  }

  public static me.sand.minecraftaimod.protobuf.Action getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Action>
      PARSER = new com.google.protobuf.AbstractParser<Action>() {
    @java.lang.Override
    public Action parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Action> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Action> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public me.sand.minecraftaimod.protobuf.Action getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

