// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: state.proto

package me.sand.minecraftaimod.protobuf;

public interface ActionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:minecraftai.Action)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated float actions = 1;</code>
   * @return A list containing the actions.
   */
  java.util.List<java.lang.Float> getActionsList();
  /**
   * <code>repeated float actions = 1;</code>
   * @return The count of actions.
   */
  int getActionsCount();
  /**
   * <code>repeated float actions = 1;</code>
   * @param index The index of the element to return.
   * @return The actions at the given index.
   */
  float getActions(int index);
}
