// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: state.proto

package me.sand.minecraftaimod.protobuf;

/**
 * Protobuf type {@code minecraftai.Matrix3D}
 */
public final class Matrix3D extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:minecraftai.Matrix3D)
    Matrix3DOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Matrix3D.newBuilder() to construct.
  private Matrix3D(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Matrix3D() {
    matrix_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Matrix3D();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return me.sand.minecraftaimod.protobuf.StateOuterClass.internal_static_minecraftai_Matrix3D_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return me.sand.minecraftaimod.protobuf.StateOuterClass.internal_static_minecraftai_Matrix3D_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            me.sand.minecraftaimod.protobuf.Matrix3D.class, me.sand.minecraftaimod.protobuf.Matrix3D.Builder.class);
  }

  public static final int MATRIX_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<me.sand.minecraftaimod.protobuf.Matrix> matrix_;
  /**
   * <code>repeated .minecraftai.Matrix matrix = 1;</code>
   */
  @java.lang.Override
  public java.util.List<me.sand.minecraftaimod.protobuf.Matrix> getMatrixList() {
    return matrix_;
  }
  /**
   * <code>repeated .minecraftai.Matrix matrix = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends me.sand.minecraftaimod.protobuf.MatrixOrBuilder> 
      getMatrixOrBuilderList() {
    return matrix_;
  }
  /**
   * <code>repeated .minecraftai.Matrix matrix = 1;</code>
   */
  @java.lang.Override
  public int getMatrixCount() {
    return matrix_.size();
  }
  /**
   * <code>repeated .minecraftai.Matrix matrix = 1;</code>
   */
  @java.lang.Override
  public me.sand.minecraftaimod.protobuf.Matrix getMatrix(int index) {
    return matrix_.get(index);
  }
  /**
   * <code>repeated .minecraftai.Matrix matrix = 1;</code>
   */
  @java.lang.Override
  public me.sand.minecraftaimod.protobuf.MatrixOrBuilder getMatrixOrBuilder(
      int index) {
    return matrix_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < matrix_.size(); i++) {
      output.writeMessage(1, matrix_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < matrix_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, matrix_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof me.sand.minecraftaimod.protobuf.Matrix3D)) {
      return super.equals(obj);
    }
    me.sand.minecraftaimod.protobuf.Matrix3D other = (me.sand.minecraftaimod.protobuf.Matrix3D) obj;

    if (!getMatrixList()
        .equals(other.getMatrixList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getMatrixCount() > 0) {
      hash = (37 * hash) + MATRIX_FIELD_NUMBER;
      hash = (53 * hash) + getMatrixList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static me.sand.minecraftaimod.protobuf.Matrix3D parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static me.sand.minecraftaimod.protobuf.Matrix3D parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static me.sand.minecraftaimod.protobuf.Matrix3D parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static me.sand.minecraftaimod.protobuf.Matrix3D parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static me.sand.minecraftaimod.protobuf.Matrix3D parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static me.sand.minecraftaimod.protobuf.Matrix3D parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static me.sand.minecraftaimod.protobuf.Matrix3D parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static me.sand.minecraftaimod.protobuf.Matrix3D parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static me.sand.minecraftaimod.protobuf.Matrix3D parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static me.sand.minecraftaimod.protobuf.Matrix3D parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static me.sand.minecraftaimod.protobuf.Matrix3D parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static me.sand.minecraftaimod.protobuf.Matrix3D parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(me.sand.minecraftaimod.protobuf.Matrix3D prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code minecraftai.Matrix3D}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:minecraftai.Matrix3D)
      me.sand.minecraftaimod.protobuf.Matrix3DOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return me.sand.minecraftaimod.protobuf.StateOuterClass.internal_static_minecraftai_Matrix3D_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return me.sand.minecraftaimod.protobuf.StateOuterClass.internal_static_minecraftai_Matrix3D_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              me.sand.minecraftaimod.protobuf.Matrix3D.class, me.sand.minecraftaimod.protobuf.Matrix3D.Builder.class);
    }

    // Construct using me.sand.minecraftaimod.protobuf.Matrix3D.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (matrixBuilder_ == null) {
        matrix_ = java.util.Collections.emptyList();
      } else {
        matrix_ = null;
        matrixBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return me.sand.minecraftaimod.protobuf.StateOuterClass.internal_static_minecraftai_Matrix3D_descriptor;
    }

    @java.lang.Override
    public me.sand.minecraftaimod.protobuf.Matrix3D getDefaultInstanceForType() {
      return me.sand.minecraftaimod.protobuf.Matrix3D.getDefaultInstance();
    }

    @java.lang.Override
    public me.sand.minecraftaimod.protobuf.Matrix3D build() {
      me.sand.minecraftaimod.protobuf.Matrix3D result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public me.sand.minecraftaimod.protobuf.Matrix3D buildPartial() {
      me.sand.minecraftaimod.protobuf.Matrix3D result = new me.sand.minecraftaimod.protobuf.Matrix3D(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(me.sand.minecraftaimod.protobuf.Matrix3D result) {
      if (matrixBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          matrix_ = java.util.Collections.unmodifiableList(matrix_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.matrix_ = matrix_;
      } else {
        result.matrix_ = matrixBuilder_.build();
      }
    }

    private void buildPartial0(me.sand.minecraftaimod.protobuf.Matrix3D result) {
      int from_bitField0_ = bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof me.sand.minecraftaimod.protobuf.Matrix3D) {
        return mergeFrom((me.sand.minecraftaimod.protobuf.Matrix3D)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(me.sand.minecraftaimod.protobuf.Matrix3D other) {
      if (other == me.sand.minecraftaimod.protobuf.Matrix3D.getDefaultInstance()) return this;
      if (matrixBuilder_ == null) {
        if (!other.matrix_.isEmpty()) {
          if (matrix_.isEmpty()) {
            matrix_ = other.matrix_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureMatrixIsMutable();
            matrix_.addAll(other.matrix_);
          }
          onChanged();
        }
      } else {
        if (!other.matrix_.isEmpty()) {
          if (matrixBuilder_.isEmpty()) {
            matrixBuilder_.dispose();
            matrixBuilder_ = null;
            matrix_ = other.matrix_;
            bitField0_ = (bitField0_ & ~0x00000001);
            matrixBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getMatrixFieldBuilder() : null;
          } else {
            matrixBuilder_.addAllMessages(other.matrix_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              me.sand.minecraftaimod.protobuf.Matrix m =
                  input.readMessage(
                      me.sand.minecraftaimod.protobuf.Matrix.parser(),
                      extensionRegistry);
              if (matrixBuilder_ == null) {
                ensureMatrixIsMutable();
                matrix_.add(m);
              } else {
                matrixBuilder_.addMessage(m);
              }
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<me.sand.minecraftaimod.protobuf.Matrix> matrix_ =
      java.util.Collections.emptyList();
    private void ensureMatrixIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        matrix_ = new java.util.ArrayList<me.sand.minecraftaimod.protobuf.Matrix>(matrix_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        me.sand.minecraftaimod.protobuf.Matrix, me.sand.minecraftaimod.protobuf.Matrix.Builder, me.sand.minecraftaimod.protobuf.MatrixOrBuilder> matrixBuilder_;

    /**
     * <code>repeated .minecraftai.Matrix matrix = 1;</code>
     */
    public java.util.List<me.sand.minecraftaimod.protobuf.Matrix> getMatrixList() {
      if (matrixBuilder_ == null) {
        return java.util.Collections.unmodifiableList(matrix_);
      } else {
        return matrixBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .minecraftai.Matrix matrix = 1;</code>
     */
    public int getMatrixCount() {
      if (matrixBuilder_ == null) {
        return matrix_.size();
      } else {
        return matrixBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .minecraftai.Matrix matrix = 1;</code>
     */
    public me.sand.minecraftaimod.protobuf.Matrix getMatrix(int index) {
      if (matrixBuilder_ == null) {
        return matrix_.get(index);
      } else {
        return matrixBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .minecraftai.Matrix matrix = 1;</code>
     */
    public Builder setMatrix(
        int index, me.sand.minecraftaimod.protobuf.Matrix value) {
      if (matrixBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMatrixIsMutable();
        matrix_.set(index, value);
        onChanged();
      } else {
        matrixBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .minecraftai.Matrix matrix = 1;</code>
     */
    public Builder setMatrix(
        int index, me.sand.minecraftaimod.protobuf.Matrix.Builder builderForValue) {
      if (matrixBuilder_ == null) {
        ensureMatrixIsMutable();
        matrix_.set(index, builderForValue.build());
        onChanged();
      } else {
        matrixBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .minecraftai.Matrix matrix = 1;</code>
     */
    public Builder addMatrix(me.sand.minecraftaimod.protobuf.Matrix value) {
      if (matrixBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMatrixIsMutable();
        matrix_.add(value);
        onChanged();
      } else {
        matrixBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .minecraftai.Matrix matrix = 1;</code>
     */
    public Builder addMatrix(
        int index, me.sand.minecraftaimod.protobuf.Matrix value) {
      if (matrixBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMatrixIsMutable();
        matrix_.add(index, value);
        onChanged();
      } else {
        matrixBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .minecraftai.Matrix matrix = 1;</code>
     */
    public Builder addMatrix(
        me.sand.minecraftaimod.protobuf.Matrix.Builder builderForValue) {
      if (matrixBuilder_ == null) {
        ensureMatrixIsMutable();
        matrix_.add(builderForValue.build());
        onChanged();
      } else {
        matrixBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .minecraftai.Matrix matrix = 1;</code>
     */
    public Builder addMatrix(
        int index, me.sand.minecraftaimod.protobuf.Matrix.Builder builderForValue) {
      if (matrixBuilder_ == null) {
        ensureMatrixIsMutable();
        matrix_.add(index, builderForValue.build());
        onChanged();
      } else {
        matrixBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .minecraftai.Matrix matrix = 1;</code>
     */
    public Builder addAllMatrix(
        java.lang.Iterable<? extends me.sand.minecraftaimod.protobuf.Matrix> values) {
      if (matrixBuilder_ == null) {
        ensureMatrixIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, matrix_);
        onChanged();
      } else {
        matrixBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .minecraftai.Matrix matrix = 1;</code>
     */
    public Builder clearMatrix() {
      if (matrixBuilder_ == null) {
        matrix_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        matrixBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .minecraftai.Matrix matrix = 1;</code>
     */
    public Builder removeMatrix(int index) {
      if (matrixBuilder_ == null) {
        ensureMatrixIsMutable();
        matrix_.remove(index);
        onChanged();
      } else {
        matrixBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .minecraftai.Matrix matrix = 1;</code>
     */
    public me.sand.minecraftaimod.protobuf.Matrix.Builder getMatrixBuilder(
        int index) {
      return getMatrixFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .minecraftai.Matrix matrix = 1;</code>
     */
    public me.sand.minecraftaimod.protobuf.MatrixOrBuilder getMatrixOrBuilder(
        int index) {
      if (matrixBuilder_ == null) {
        return matrix_.get(index);  } else {
        return matrixBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .minecraftai.Matrix matrix = 1;</code>
     */
    public java.util.List<? extends me.sand.minecraftaimod.protobuf.MatrixOrBuilder> 
         getMatrixOrBuilderList() {
      if (matrixBuilder_ != null) {
        return matrixBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(matrix_);
      }
    }
    /**
     * <code>repeated .minecraftai.Matrix matrix = 1;</code>
     */
    public me.sand.minecraftaimod.protobuf.Matrix.Builder addMatrixBuilder() {
      return getMatrixFieldBuilder().addBuilder(
          me.sand.minecraftaimod.protobuf.Matrix.getDefaultInstance());
    }
    /**
     * <code>repeated .minecraftai.Matrix matrix = 1;</code>
     */
    public me.sand.minecraftaimod.protobuf.Matrix.Builder addMatrixBuilder(
        int index) {
      return getMatrixFieldBuilder().addBuilder(
          index, me.sand.minecraftaimod.protobuf.Matrix.getDefaultInstance());
    }
    /**
     * <code>repeated .minecraftai.Matrix matrix = 1;</code>
     */
    public java.util.List<me.sand.minecraftaimod.protobuf.Matrix.Builder> 
         getMatrixBuilderList() {
      return getMatrixFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        me.sand.minecraftaimod.protobuf.Matrix, me.sand.minecraftaimod.protobuf.Matrix.Builder, me.sand.minecraftaimod.protobuf.MatrixOrBuilder> 
        getMatrixFieldBuilder() {
      if (matrixBuilder_ == null) {
        matrixBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            me.sand.minecraftaimod.protobuf.Matrix, me.sand.minecraftaimod.protobuf.Matrix.Builder, me.sand.minecraftaimod.protobuf.MatrixOrBuilder>(
                matrix_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        matrix_ = null;
      }
      return matrixBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:minecraftai.Matrix3D)
  }

  // @@protoc_insertion_point(class_scope:minecraftai.Matrix3D)
  private static final me.sand.minecraftaimod.protobuf.Matrix3D DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new me.sand.minecraftaimod.protobuf.Matrix3D();
  }

  public static me.sand.minecraftaimod.protobuf.Matrix3D getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Matrix3D>
      PARSER = new com.google.protobuf.AbstractParser<Matrix3D>() {
    @java.lang.Override
    public Matrix3D parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Matrix3D> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Matrix3D> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public me.sand.minecraftaimod.protobuf.Matrix3D getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

