// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: state.proto

package me.sand.minecraftaimod.protobuf;

/**
 * Protobuf type {@code minecraftai.Matrix4D}
 */
public final class Matrix4D extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:minecraftai.Matrix4D)
    Matrix4DOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Matrix4D.newBuilder() to construct.
  private Matrix4D(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Matrix4D() {
    matrix3D_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Matrix4D();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return me.sand.minecraftaimod.protobuf.StateOuterClass.internal_static_minecraftai_Matrix4D_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return me.sand.minecraftaimod.protobuf.StateOuterClass.internal_static_minecraftai_Matrix4D_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            me.sand.minecraftaimod.protobuf.Matrix4D.class, me.sand.minecraftaimod.protobuf.Matrix4D.Builder.class);
  }

  public static final int MATRIX3D_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<me.sand.minecraftaimod.protobuf.Matrix3D> matrix3D_;
  /**
   * <code>repeated .minecraftai.Matrix3D matrix3D = 1;</code>
   */
  @java.lang.Override
  public java.util.List<me.sand.minecraftaimod.protobuf.Matrix3D> getMatrix3DList() {
    return matrix3D_;
  }
  /**
   * <code>repeated .minecraftai.Matrix3D matrix3D = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends me.sand.minecraftaimod.protobuf.Matrix3DOrBuilder> 
      getMatrix3DOrBuilderList() {
    return matrix3D_;
  }
  /**
   * <code>repeated .minecraftai.Matrix3D matrix3D = 1;</code>
   */
  @java.lang.Override
  public int getMatrix3DCount() {
    return matrix3D_.size();
  }
  /**
   * <code>repeated .minecraftai.Matrix3D matrix3D = 1;</code>
   */
  @java.lang.Override
  public me.sand.minecraftaimod.protobuf.Matrix3D getMatrix3D(int index) {
    return matrix3D_.get(index);
  }
  /**
   * <code>repeated .minecraftai.Matrix3D matrix3D = 1;</code>
   */
  @java.lang.Override
  public me.sand.minecraftaimod.protobuf.Matrix3DOrBuilder getMatrix3DOrBuilder(
      int index) {
    return matrix3D_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < matrix3D_.size(); i++) {
      output.writeMessage(1, matrix3D_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < matrix3D_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, matrix3D_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof me.sand.minecraftaimod.protobuf.Matrix4D)) {
      return super.equals(obj);
    }
    me.sand.minecraftaimod.protobuf.Matrix4D other = (me.sand.minecraftaimod.protobuf.Matrix4D) obj;

    if (!getMatrix3DList()
        .equals(other.getMatrix3DList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getMatrix3DCount() > 0) {
      hash = (37 * hash) + MATRIX3D_FIELD_NUMBER;
      hash = (53 * hash) + getMatrix3DList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static me.sand.minecraftaimod.protobuf.Matrix4D parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static me.sand.minecraftaimod.protobuf.Matrix4D parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static me.sand.minecraftaimod.protobuf.Matrix4D parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static me.sand.minecraftaimod.protobuf.Matrix4D parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static me.sand.minecraftaimod.protobuf.Matrix4D parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static me.sand.minecraftaimod.protobuf.Matrix4D parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static me.sand.minecraftaimod.protobuf.Matrix4D parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static me.sand.minecraftaimod.protobuf.Matrix4D parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static me.sand.minecraftaimod.protobuf.Matrix4D parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static me.sand.minecraftaimod.protobuf.Matrix4D parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static me.sand.minecraftaimod.protobuf.Matrix4D parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static me.sand.minecraftaimod.protobuf.Matrix4D parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(me.sand.minecraftaimod.protobuf.Matrix4D prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code minecraftai.Matrix4D}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:minecraftai.Matrix4D)
      me.sand.minecraftaimod.protobuf.Matrix4DOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return me.sand.minecraftaimod.protobuf.StateOuterClass.internal_static_minecraftai_Matrix4D_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return me.sand.minecraftaimod.protobuf.StateOuterClass.internal_static_minecraftai_Matrix4D_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              me.sand.minecraftaimod.protobuf.Matrix4D.class, me.sand.minecraftaimod.protobuf.Matrix4D.Builder.class);
    }

    // Construct using me.sand.minecraftaimod.protobuf.Matrix4D.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (matrix3DBuilder_ == null) {
        matrix3D_ = java.util.Collections.emptyList();
      } else {
        matrix3D_ = null;
        matrix3DBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return me.sand.minecraftaimod.protobuf.StateOuterClass.internal_static_minecraftai_Matrix4D_descriptor;
    }

    @java.lang.Override
    public me.sand.minecraftaimod.protobuf.Matrix4D getDefaultInstanceForType() {
      return me.sand.minecraftaimod.protobuf.Matrix4D.getDefaultInstance();
    }

    @java.lang.Override
    public me.sand.minecraftaimod.protobuf.Matrix4D build() {
      me.sand.minecraftaimod.protobuf.Matrix4D result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public me.sand.minecraftaimod.protobuf.Matrix4D buildPartial() {
      me.sand.minecraftaimod.protobuf.Matrix4D result = new me.sand.minecraftaimod.protobuf.Matrix4D(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(me.sand.minecraftaimod.protobuf.Matrix4D result) {
      if (matrix3DBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          matrix3D_ = java.util.Collections.unmodifiableList(matrix3D_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.matrix3D_ = matrix3D_;
      } else {
        result.matrix3D_ = matrix3DBuilder_.build();
      }
    }

    private void buildPartial0(me.sand.minecraftaimod.protobuf.Matrix4D result) {
      int from_bitField0_ = bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof me.sand.minecraftaimod.protobuf.Matrix4D) {
        return mergeFrom((me.sand.minecraftaimod.protobuf.Matrix4D)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(me.sand.minecraftaimod.protobuf.Matrix4D other) {
      if (other == me.sand.minecraftaimod.protobuf.Matrix4D.getDefaultInstance()) return this;
      if (matrix3DBuilder_ == null) {
        if (!other.matrix3D_.isEmpty()) {
          if (matrix3D_.isEmpty()) {
            matrix3D_ = other.matrix3D_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureMatrix3DIsMutable();
            matrix3D_.addAll(other.matrix3D_);
          }
          onChanged();
        }
      } else {
        if (!other.matrix3D_.isEmpty()) {
          if (matrix3DBuilder_.isEmpty()) {
            matrix3DBuilder_.dispose();
            matrix3DBuilder_ = null;
            matrix3D_ = other.matrix3D_;
            bitField0_ = (bitField0_ & ~0x00000001);
            matrix3DBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getMatrix3DFieldBuilder() : null;
          } else {
            matrix3DBuilder_.addAllMessages(other.matrix3D_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              me.sand.minecraftaimod.protobuf.Matrix3D m =
                  input.readMessage(
                      me.sand.minecraftaimod.protobuf.Matrix3D.parser(),
                      extensionRegistry);
              if (matrix3DBuilder_ == null) {
                ensureMatrix3DIsMutable();
                matrix3D_.add(m);
              } else {
                matrix3DBuilder_.addMessage(m);
              }
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<me.sand.minecraftaimod.protobuf.Matrix3D> matrix3D_ =
      java.util.Collections.emptyList();
    private void ensureMatrix3DIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        matrix3D_ = new java.util.ArrayList<me.sand.minecraftaimod.protobuf.Matrix3D>(matrix3D_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        me.sand.minecraftaimod.protobuf.Matrix3D, me.sand.minecraftaimod.protobuf.Matrix3D.Builder, me.sand.minecraftaimod.protobuf.Matrix3DOrBuilder> matrix3DBuilder_;

    /**
     * <code>repeated .minecraftai.Matrix3D matrix3D = 1;</code>
     */
    public java.util.List<me.sand.minecraftaimod.protobuf.Matrix3D> getMatrix3DList() {
      if (matrix3DBuilder_ == null) {
        return java.util.Collections.unmodifiableList(matrix3D_);
      } else {
        return matrix3DBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .minecraftai.Matrix3D matrix3D = 1;</code>
     */
    public int getMatrix3DCount() {
      if (matrix3DBuilder_ == null) {
        return matrix3D_.size();
      } else {
        return matrix3DBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .minecraftai.Matrix3D matrix3D = 1;</code>
     */
    public me.sand.minecraftaimod.protobuf.Matrix3D getMatrix3D(int index) {
      if (matrix3DBuilder_ == null) {
        return matrix3D_.get(index);
      } else {
        return matrix3DBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .minecraftai.Matrix3D matrix3D = 1;</code>
     */
    public Builder setMatrix3D(
        int index, me.sand.minecraftaimod.protobuf.Matrix3D value) {
      if (matrix3DBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMatrix3DIsMutable();
        matrix3D_.set(index, value);
        onChanged();
      } else {
        matrix3DBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .minecraftai.Matrix3D matrix3D = 1;</code>
     */
    public Builder setMatrix3D(
        int index, me.sand.minecraftaimod.protobuf.Matrix3D.Builder builderForValue) {
      if (matrix3DBuilder_ == null) {
        ensureMatrix3DIsMutable();
        matrix3D_.set(index, builderForValue.build());
        onChanged();
      } else {
        matrix3DBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .minecraftai.Matrix3D matrix3D = 1;</code>
     */
    public Builder addMatrix3D(me.sand.minecraftaimod.protobuf.Matrix3D value) {
      if (matrix3DBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMatrix3DIsMutable();
        matrix3D_.add(value);
        onChanged();
      } else {
        matrix3DBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .minecraftai.Matrix3D matrix3D = 1;</code>
     */
    public Builder addMatrix3D(
        int index, me.sand.minecraftaimod.protobuf.Matrix3D value) {
      if (matrix3DBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMatrix3DIsMutable();
        matrix3D_.add(index, value);
        onChanged();
      } else {
        matrix3DBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .minecraftai.Matrix3D matrix3D = 1;</code>
     */
    public Builder addMatrix3D(
        me.sand.minecraftaimod.protobuf.Matrix3D.Builder builderForValue) {
      if (matrix3DBuilder_ == null) {
        ensureMatrix3DIsMutable();
        matrix3D_.add(builderForValue.build());
        onChanged();
      } else {
        matrix3DBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .minecraftai.Matrix3D matrix3D = 1;</code>
     */
    public Builder addMatrix3D(
        int index, me.sand.minecraftaimod.protobuf.Matrix3D.Builder builderForValue) {
      if (matrix3DBuilder_ == null) {
        ensureMatrix3DIsMutable();
        matrix3D_.add(index, builderForValue.build());
        onChanged();
      } else {
        matrix3DBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .minecraftai.Matrix3D matrix3D = 1;</code>
     */
    public Builder addAllMatrix3D(
        java.lang.Iterable<? extends me.sand.minecraftaimod.protobuf.Matrix3D> values) {
      if (matrix3DBuilder_ == null) {
        ensureMatrix3DIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, matrix3D_);
        onChanged();
      } else {
        matrix3DBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .minecraftai.Matrix3D matrix3D = 1;</code>
     */
    public Builder clearMatrix3D() {
      if (matrix3DBuilder_ == null) {
        matrix3D_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        matrix3DBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .minecraftai.Matrix3D matrix3D = 1;</code>
     */
    public Builder removeMatrix3D(int index) {
      if (matrix3DBuilder_ == null) {
        ensureMatrix3DIsMutable();
        matrix3D_.remove(index);
        onChanged();
      } else {
        matrix3DBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .minecraftai.Matrix3D matrix3D = 1;</code>
     */
    public me.sand.minecraftaimod.protobuf.Matrix3D.Builder getMatrix3DBuilder(
        int index) {
      return getMatrix3DFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .minecraftai.Matrix3D matrix3D = 1;</code>
     */
    public me.sand.minecraftaimod.protobuf.Matrix3DOrBuilder getMatrix3DOrBuilder(
        int index) {
      if (matrix3DBuilder_ == null) {
        return matrix3D_.get(index);  } else {
        return matrix3DBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .minecraftai.Matrix3D matrix3D = 1;</code>
     */
    public java.util.List<? extends me.sand.minecraftaimod.protobuf.Matrix3DOrBuilder> 
         getMatrix3DOrBuilderList() {
      if (matrix3DBuilder_ != null) {
        return matrix3DBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(matrix3D_);
      }
    }
    /**
     * <code>repeated .minecraftai.Matrix3D matrix3D = 1;</code>
     */
    public me.sand.minecraftaimod.protobuf.Matrix3D.Builder addMatrix3DBuilder() {
      return getMatrix3DFieldBuilder().addBuilder(
          me.sand.minecraftaimod.protobuf.Matrix3D.getDefaultInstance());
    }
    /**
     * <code>repeated .minecraftai.Matrix3D matrix3D = 1;</code>
     */
    public me.sand.minecraftaimod.protobuf.Matrix3D.Builder addMatrix3DBuilder(
        int index) {
      return getMatrix3DFieldBuilder().addBuilder(
          index, me.sand.minecraftaimod.protobuf.Matrix3D.getDefaultInstance());
    }
    /**
     * <code>repeated .minecraftai.Matrix3D matrix3D = 1;</code>
     */
    public java.util.List<me.sand.minecraftaimod.protobuf.Matrix3D.Builder> 
         getMatrix3DBuilderList() {
      return getMatrix3DFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        me.sand.minecraftaimod.protobuf.Matrix3D, me.sand.minecraftaimod.protobuf.Matrix3D.Builder, me.sand.minecraftaimod.protobuf.Matrix3DOrBuilder> 
        getMatrix3DFieldBuilder() {
      if (matrix3DBuilder_ == null) {
        matrix3DBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            me.sand.minecraftaimod.protobuf.Matrix3D, me.sand.minecraftaimod.protobuf.Matrix3D.Builder, me.sand.minecraftaimod.protobuf.Matrix3DOrBuilder>(
                matrix3D_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        matrix3D_ = null;
      }
      return matrix3DBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:minecraftai.Matrix4D)
  }

  // @@protoc_insertion_point(class_scope:minecraftai.Matrix4D)
  private static final me.sand.minecraftaimod.protobuf.Matrix4D DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new me.sand.minecraftaimod.protobuf.Matrix4D();
  }

  public static me.sand.minecraftaimod.protobuf.Matrix4D getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Matrix4D>
      PARSER = new com.google.protobuf.AbstractParser<Matrix4D>() {
    @java.lang.Override
    public Matrix4D parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Matrix4D> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Matrix4D> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public me.sand.minecraftaimod.protobuf.Matrix4D getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

