// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: state.proto

package me.sand.minecraftaimod.protobuf;

public interface Matrix4DOrBuilder extends
    // @@protoc_insertion_point(interface_extends:minecraftai.Matrix4D)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .minecraftai.Matrix3D matrix3D = 1;</code>
   */
  java.util.List<me.sand.minecraftaimod.protobuf.Matrix3D> 
      getMatrix3DList();
  /**
   * <code>repeated .minecraftai.Matrix3D matrix3D = 1;</code>
   */
  me.sand.minecraftaimod.protobuf.Matrix3D getMatrix3D(int index);
  /**
   * <code>repeated .minecraftai.Matrix3D matrix3D = 1;</code>
   */
  int getMatrix3DCount();
  /**
   * <code>repeated .minecraftai.Matrix3D matrix3D = 1;</code>
   */
  java.util.List<? extends me.sand.minecraftaimod.protobuf.Matrix3DOrBuilder> 
      getMatrix3DOrBuilderList();
  /**
   * <code>repeated .minecraftai.Matrix3D matrix3D = 1;</code>
   */
  me.sand.minecraftaimod.protobuf.Matrix3DOrBuilder getMatrix3DOrBuilder(
      int index);
}
