// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: state.proto

package me.sand.minecraftaimod.protobuf;

public interface MatrixOrBuilder extends
    // @@protoc_insertion_point(interface_extends:minecraftai.Matrix)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .minecraftai.Row rows = 1;</code>
   */
  java.util.List<me.sand.minecraftaimod.protobuf.Row> 
      getRowsList();
  /**
   * <code>repeated .minecraftai.Row rows = 1;</code>
   */
  me.sand.minecraftaimod.protobuf.Row getRows(int index);
  /**
   * <code>repeated .minecraftai.Row rows = 1;</code>
   */
  int getRowsCount();
  /**
   * <code>repeated .minecraftai.Row rows = 1;</code>
   */
  java.util.List<? extends me.sand.minecraftaimod.protobuf.RowOrBuilder> 
      getRowsOrBuilderList();
  /**
   * <code>repeated .minecraftai.Row rows = 1;</code>
   */
  me.sand.minecraftaimod.protobuf.RowOrBuilder getRowsOrBuilder(
      int index);
}
