// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: state.proto

package me.sand.minecraftaimod.protobuf;

public interface Matrix3DOrBuilder extends
    // @@protoc_insertion_point(interface_extends:minecraftai.Matrix3D)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .minecraftai.Matrix matrix = 1;</code>
   */
  java.util.List<me.sand.minecraftaimod.protobuf.Matrix> 
      getMatrixList();
  /**
   * <code>repeated .minecraftai.Matrix matrix = 1;</code>
   */
  me.sand.minecraftaimod.protobuf.Matrix getMatrix(int index);
  /**
   * <code>repeated .minecraftai.Matrix matrix = 1;</code>
   */
  int getMatrixCount();
  /**
   * <code>repeated .minecraftai.Matrix matrix = 1;</code>
   */
  java.util.List<? extends me.sand.minecraftaimod.protobuf.MatrixOrBuilder> 
      getMatrixOrBuilderList();
  /**
   * <code>repeated .minecraftai.Matrix matrix = 1;</code>
   */
  me.sand.minecraftaimod.protobuf.MatrixOrBuilder getMatrixOrBuilder(
      int index);
}
