// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: state.proto

package me.sand.minecraftaimod.protobuf;

public interface RowOrBuilder extends
    // @@protoc_insertion_point(interface_extends:minecraftai.Row)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated double values = 1;</code>
   * @return A list containing the values.
   */
  java.util.List<java.lang.Double> getValuesList();
  /**
   * <code>repeated double values = 1;</code>
   * @return The count of values.
   */
  int getValuesCount();
  /**
   * <code>repeated double values = 1;</code>
   * @param index The index of the element to return.
   * @return The values at the given index.
   */
  double getValues(int index);
}
