// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: state.proto

package me.sand.minecraftaimod.protobuf;

public interface StateOrBuilder extends
    // @@protoc_insertion_point(interface_extends:minecraftai.State)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated double agentInfo = 1;</code>
   * @return A list containing the agentInfo.
   */
  java.util.List<java.lang.Double> getAgentInfoList();
  /**
   * <code>repeated double agentInfo = 1;</code>
   * @return The count of agentInfo.
   */
  int getAgentInfoCount();
  /**
   * <code>repeated double agentInfo = 1;</code>
   * @param index The index of the element to return.
   * @return The agentInfo at the given index.
   */
  double getAgentInfo(int index);

  /**
   * <code>.minecraftai.Matrix inventory = 2;</code>
   * @return Whether the inventory field is set.
   */
  boolean hasInventory();
  /**
   * <code>.minecraftai.Matrix inventory = 2;</code>
   * @return The inventory.
   */
  me.sand.minecraftaimod.protobuf.Matrix getInventory();
  /**
   * <code>.minecraftai.Matrix inventory = 2;</code>
   */
  me.sand.minecraftaimod.protobuf.MatrixOrBuilder getInventoryOrBuilder();

  /**
   * <code>.minecraftai.Matrix nearbyEntities = 3;</code>
   * @return Whether the nearbyEntities field is set.
   */
  boolean hasNearbyEntities();
  /**
   * <code>.minecraftai.Matrix nearbyEntities = 3;</code>
   * @return The nearbyEntities.
   */
  me.sand.minecraftaimod.protobuf.Matrix getNearbyEntities();
  /**
   * <code>.minecraftai.Matrix nearbyEntities = 3;</code>
   */
  me.sand.minecraftaimod.protobuf.MatrixOrBuilder getNearbyEntitiesOrBuilder();

  /**
   * <code>.minecraftai.Matrix nearbyBlocks = 4;</code>
   * @return Whether the nearbyBlocks field is set.
   */
  boolean hasNearbyBlocks();
  /**
   * <code>.minecraftai.Matrix nearbyBlocks = 4;</code>
   * @return The nearbyBlocks.
   */
  me.sand.minecraftaimod.protobuf.Matrix getNearbyBlocks();
  /**
   * <code>.minecraftai.Matrix nearbyBlocks = 4;</code>
   */
  me.sand.minecraftaimod.protobuf.MatrixOrBuilder getNearbyBlocksOrBuilder();
}
