// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: state.proto

package me.sand.minecraftaimod.protobuf;

public interface StateOrBuilder extends
    // @@protoc_insertion_point(interface_extends:minecraftai.State)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated double agentInfo = 1;</code>
   * @return A list containing the agentInfo.
   */
  java.util.List<java.lang.Double> getAgentInfoList();
  /**
   * <code>repeated double agentInfo = 1;</code>
   * @return The count of agentInfo.
   */
  int getAgentInfoCount();
  /**
   * <code>repeated double agentInfo = 1;</code>
   * @param index The index of the element to return.
   * @return The agentInfo at the given index.
   */
  double getAgentInfo(int index);

  /**
   * <code>.minecraftai.Matrix inventory = 2;</code>
   * @return Whether the inventory field is set.
   */
  boolean hasInventory();
  /**
   * <code>.minecraftai.Matrix inventory = 2;</code>
   * @return The inventory.
   */
  me.sand.minecraftaimod.protobuf.Matrix getInventory();
  /**
   * <code>.minecraftai.Matrix inventory = 2;</code>
   */
  me.sand.minecraftaimod.protobuf.MatrixOrBuilder getInventoryOrBuilder();

  /**
   * <code>.minecraftai.Matrix nearbyEntities = 3;</code>
   * @return Whether the nearbyEntities field is set.
   */
  boolean hasNearbyEntities();
  /**
   * <code>.minecraftai.Matrix nearbyEntities = 3;</code>
   * @return The nearbyEntities.
   */
  me.sand.minecraftaimod.protobuf.Matrix getNearbyEntities();
  /**
   * <code>.minecraftai.Matrix nearbyEntities = 3;</code>
   */
  me.sand.minecraftaimod.protobuf.MatrixOrBuilder getNearbyEntitiesOrBuilder();

  /**
   * <code>.minecraftai.Matrix3D nearbyBlocks = 4;</code>
   * @return Whether the nearbyBlocks field is set.
   */
  boolean hasNearbyBlocks();
  /**
   * <code>.minecraftai.Matrix3D nearbyBlocks = 4;</code>
   * @return The nearbyBlocks.
   */
  me.sand.minecraftaimod.protobuf.Matrix3D getNearbyBlocks();
  /**
   * <code>.minecraftai.Matrix3D nearbyBlocks = 4;</code>
   */
  me.sand.minecraftaimod.protobuf.Matrix3DOrBuilder getNearbyBlocksOrBuilder();

  /**
   * <code>.minecraftai.Matrix4D nearbyItemDrops = 5;</code>
   * @return Whether the nearbyItemDrops field is set.
   */
  boolean hasNearbyItemDrops();
  /**
   * <code>.minecraftai.Matrix4D nearbyItemDrops = 5;</code>
   * @return The nearbyItemDrops.
   */
  me.sand.minecraftaimod.protobuf.Matrix4D getNearbyItemDrops();
  /**
   * <code>.minecraftai.Matrix4D nearbyItemDrops = 5;</code>
   */
  me.sand.minecraftaimod.protobuf.Matrix4DOrBuilder getNearbyItemDropsOrBuilder();

  /**
   * <code>.minecraftai.Matrix container = 6;</code>
   * @return Whether the container field is set.
   */
  boolean hasContainer();
  /**
   * <code>.minecraftai.Matrix container = 6;</code>
   * @return The container.
   */
  me.sand.minecraftaimod.protobuf.Matrix getContainer();
  /**
   * <code>.minecraftai.Matrix container = 6;</code>
   */
  me.sand.minecraftaimod.protobuf.MatrixOrBuilder getContainerOrBuilder();

  /**
   * <code>double containerType = 7;</code>
   * @return The containerType.
   */
  double getContainerType();

  /**
   * <code>repeated double containerMask = 8;</code>
   * @return A list containing the containerMask.
   */
  java.util.List<java.lang.Double> getContainerMaskList();
  /**
   * <code>repeated double containerMask = 8;</code>
   * @return The count of containerMask.
   */
  int getContainerMaskCount();
  /**
   * <code>repeated double containerMask = 8;</code>
   * @param index The index of the element to return.
   * @return The containerMask at the given index.
   */
  double getContainerMask(int index);

  /**
   * <code>repeated double isWalkable = 9;</code>
   * @return A list containing the isWalkable.
   */
  java.util.List<java.lang.Double> getIsWalkableList();
  /**
   * <code>repeated double isWalkable = 9;</code>
   * @return The count of isWalkable.
   */
  int getIsWalkableCount();
  /**
   * <code>repeated double isWalkable = 9;</code>
   * @param index The index of the element to return.
   * @return The isWalkable at the given index.
   */
  double getIsWalkable(int index);
}
