// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: state.proto

package me.sand.minecraftaimod.protobuf;

/**
 * Protobuf type {@code minecraftai.State}
 */
public final class State extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:minecraftai.State)
    StateOrBuilder {
private static final long serialVersionUID = 0L;
  // Use State.newBuilder() to construct.
  private State(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private State() {
    agentInfo_ = emptyDoubleList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new State();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return me.sand.minecraftaimod.protobuf.StateOuterClass.internal_static_minecraftai_State_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return me.sand.minecraftaimod.protobuf.StateOuterClass.internal_static_minecraftai_State_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            me.sand.minecraftaimod.protobuf.State.class, me.sand.minecraftaimod.protobuf.State.Builder.class);
  }

  public static final int AGENTINFO_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private com.google.protobuf.Internal.DoubleList agentInfo_;
  /**
   * <code>repeated double agentInfo = 1;</code>
   * @return A list containing the agentInfo.
   */
  @java.lang.Override
  public java.util.List<java.lang.Double>
      getAgentInfoList() {
    return agentInfo_;
  }
  /**
   * <code>repeated double agentInfo = 1;</code>
   * @return The count of agentInfo.
   */
  public int getAgentInfoCount() {
    return agentInfo_.size();
  }
  /**
   * <code>repeated double agentInfo = 1;</code>
   * @param index The index of the element to return.
   * @return The agentInfo at the given index.
   */
  public double getAgentInfo(int index) {
    return agentInfo_.getDouble(index);
  }
  private int agentInfoMemoizedSerializedSize = -1;

  public static final int INVENTORY_FIELD_NUMBER = 2;
  private me.sand.minecraftaimod.protobuf.Matrix inventory_;
  /**
   * <code>.minecraftai.Matrix inventory = 2;</code>
   * @return Whether the inventory field is set.
   */
  @java.lang.Override
  public boolean hasInventory() {
    return inventory_ != null;
  }
  /**
   * <code>.minecraftai.Matrix inventory = 2;</code>
   * @return The inventory.
   */
  @java.lang.Override
  public me.sand.minecraftaimod.protobuf.Matrix getInventory() {
    return inventory_ == null ? me.sand.minecraftaimod.protobuf.Matrix.getDefaultInstance() : inventory_;
  }
  /**
   * <code>.minecraftai.Matrix inventory = 2;</code>
   */
  @java.lang.Override
  public me.sand.minecraftaimod.protobuf.MatrixOrBuilder getInventoryOrBuilder() {
    return inventory_ == null ? me.sand.minecraftaimod.protobuf.Matrix.getDefaultInstance() : inventory_;
  }

  public static final int NEARBYENTITIES_FIELD_NUMBER = 3;
  private me.sand.minecraftaimod.protobuf.Matrix nearbyEntities_;
  /**
   * <code>.minecraftai.Matrix nearbyEntities = 3;</code>
   * @return Whether the nearbyEntities field is set.
   */
  @java.lang.Override
  public boolean hasNearbyEntities() {
    return nearbyEntities_ != null;
  }
  /**
   * <code>.minecraftai.Matrix nearbyEntities = 3;</code>
   * @return The nearbyEntities.
   */
  @java.lang.Override
  public me.sand.minecraftaimod.protobuf.Matrix getNearbyEntities() {
    return nearbyEntities_ == null ? me.sand.minecraftaimod.protobuf.Matrix.getDefaultInstance() : nearbyEntities_;
  }
  /**
   * <code>.minecraftai.Matrix nearbyEntities = 3;</code>
   */
  @java.lang.Override
  public me.sand.minecraftaimod.protobuf.MatrixOrBuilder getNearbyEntitiesOrBuilder() {
    return nearbyEntities_ == null ? me.sand.minecraftaimod.protobuf.Matrix.getDefaultInstance() : nearbyEntities_;
  }

  public static final int NEARBYBLOCKS_FIELD_NUMBER = 4;
  private me.sand.minecraftaimod.protobuf.Matrix3D nearbyBlocks_;
  /**
   * <code>.minecraftai.Matrix3D nearbyBlocks = 4;</code>
   * @return Whether the nearbyBlocks field is set.
   */
  @java.lang.Override
  public boolean hasNearbyBlocks() {
    return nearbyBlocks_ != null;
  }
  /**
   * <code>.minecraftai.Matrix3D nearbyBlocks = 4;</code>
   * @return The nearbyBlocks.
   */
  @java.lang.Override
  public me.sand.minecraftaimod.protobuf.Matrix3D getNearbyBlocks() {
    return nearbyBlocks_ == null ? me.sand.minecraftaimod.protobuf.Matrix3D.getDefaultInstance() : nearbyBlocks_;
  }
  /**
   * <code>.minecraftai.Matrix3D nearbyBlocks = 4;</code>
   */
  @java.lang.Override
  public me.sand.minecraftaimod.protobuf.Matrix3DOrBuilder getNearbyBlocksOrBuilder() {
    return nearbyBlocks_ == null ? me.sand.minecraftaimod.protobuf.Matrix3D.getDefaultInstance() : nearbyBlocks_;
  }

  public static final int NEARBYITEMDROPS_FIELD_NUMBER = 5;
  private me.sand.minecraftaimod.protobuf.Matrix4D nearbyItemDrops_;
  /**
   * <code>.minecraftai.Matrix4D nearbyItemDrops = 5;</code>
   * @return Whether the nearbyItemDrops field is set.
   */
  @java.lang.Override
  public boolean hasNearbyItemDrops() {
    return nearbyItemDrops_ != null;
  }
  /**
   * <code>.minecraftai.Matrix4D nearbyItemDrops = 5;</code>
   * @return The nearbyItemDrops.
   */
  @java.lang.Override
  public me.sand.minecraftaimod.protobuf.Matrix4D getNearbyItemDrops() {
    return nearbyItemDrops_ == null ? me.sand.minecraftaimod.protobuf.Matrix4D.getDefaultInstance() : nearbyItemDrops_;
  }
  /**
   * <code>.minecraftai.Matrix4D nearbyItemDrops = 5;</code>
   */
  @java.lang.Override
  public me.sand.minecraftaimod.protobuf.Matrix4DOrBuilder getNearbyItemDropsOrBuilder() {
    return nearbyItemDrops_ == null ? me.sand.minecraftaimod.protobuf.Matrix4D.getDefaultInstance() : nearbyItemDrops_;
  }

  public static final int CONTAINER_FIELD_NUMBER = 6;
  private me.sand.minecraftaimod.protobuf.Matrix container_;
  /**
   * <code>.minecraftai.Matrix container = 6;</code>
   * @return Whether the container field is set.
   */
  @java.lang.Override
  public boolean hasContainer() {
    return container_ != null;
  }
  /**
   * <code>.minecraftai.Matrix container = 6;</code>
   * @return The container.
   */
  @java.lang.Override
  public me.sand.minecraftaimod.protobuf.Matrix getContainer() {
    return container_ == null ? me.sand.minecraftaimod.protobuf.Matrix.getDefaultInstance() : container_;
  }
  /**
   * <code>.minecraftai.Matrix container = 6;</code>
   */
  @java.lang.Override
  public me.sand.minecraftaimod.protobuf.MatrixOrBuilder getContainerOrBuilder() {
    return container_ == null ? me.sand.minecraftaimod.protobuf.Matrix.getDefaultInstance() : container_;
  }

  public static final int CONTAINERTYPE_FIELD_NUMBER = 7;
  private double containerType_ = 0D;
  /**
   * <code>double containerType = 7;</code>
   * @return The containerType.
   */
  @java.lang.Override
  public double getContainerType() {
    return containerType_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (getAgentInfoList().size() > 0) {
      output.writeUInt32NoTag(10);
      output.writeUInt32NoTag(agentInfoMemoizedSerializedSize);
    }
    for (int i = 0; i < agentInfo_.size(); i++) {
      output.writeDoubleNoTag(agentInfo_.getDouble(i));
    }
    if (inventory_ != null) {
      output.writeMessage(2, getInventory());
    }
    if (nearbyEntities_ != null) {
      output.writeMessage(3, getNearbyEntities());
    }
    if (nearbyBlocks_ != null) {
      output.writeMessage(4, getNearbyBlocks());
    }
    if (nearbyItemDrops_ != null) {
      output.writeMessage(5, getNearbyItemDrops());
    }
    if (container_ != null) {
      output.writeMessage(6, getContainer());
    }
    if (java.lang.Double.doubleToRawLongBits(containerType_) != 0) {
      output.writeDouble(7, containerType_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      dataSize = 8 * getAgentInfoList().size();
      size += dataSize;
      if (!getAgentInfoList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      agentInfoMemoizedSerializedSize = dataSize;
    }
    if (inventory_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getInventory());
    }
    if (nearbyEntities_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getNearbyEntities());
    }
    if (nearbyBlocks_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getNearbyBlocks());
    }
    if (nearbyItemDrops_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getNearbyItemDrops());
    }
    if (container_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, getContainer());
    }
    if (java.lang.Double.doubleToRawLongBits(containerType_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(7, containerType_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof me.sand.minecraftaimod.protobuf.State)) {
      return super.equals(obj);
    }
    me.sand.minecraftaimod.protobuf.State other = (me.sand.minecraftaimod.protobuf.State) obj;

    if (!getAgentInfoList()
        .equals(other.getAgentInfoList())) return false;
    if (hasInventory() != other.hasInventory()) return false;
    if (hasInventory()) {
      if (!getInventory()
          .equals(other.getInventory())) return false;
    }
    if (hasNearbyEntities() != other.hasNearbyEntities()) return false;
    if (hasNearbyEntities()) {
      if (!getNearbyEntities()
          .equals(other.getNearbyEntities())) return false;
    }
    if (hasNearbyBlocks() != other.hasNearbyBlocks()) return false;
    if (hasNearbyBlocks()) {
      if (!getNearbyBlocks()
          .equals(other.getNearbyBlocks())) return false;
    }
    if (hasNearbyItemDrops() != other.hasNearbyItemDrops()) return false;
    if (hasNearbyItemDrops()) {
      if (!getNearbyItemDrops()
          .equals(other.getNearbyItemDrops())) return false;
    }
    if (hasContainer() != other.hasContainer()) return false;
    if (hasContainer()) {
      if (!getContainer()
          .equals(other.getContainer())) return false;
    }
    if (java.lang.Double.doubleToLongBits(getContainerType())
        != java.lang.Double.doubleToLongBits(
            other.getContainerType())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getAgentInfoCount() > 0) {
      hash = (37 * hash) + AGENTINFO_FIELD_NUMBER;
      hash = (53 * hash) + getAgentInfoList().hashCode();
    }
    if (hasInventory()) {
      hash = (37 * hash) + INVENTORY_FIELD_NUMBER;
      hash = (53 * hash) + getInventory().hashCode();
    }
    if (hasNearbyEntities()) {
      hash = (37 * hash) + NEARBYENTITIES_FIELD_NUMBER;
      hash = (53 * hash) + getNearbyEntities().hashCode();
    }
    if (hasNearbyBlocks()) {
      hash = (37 * hash) + NEARBYBLOCKS_FIELD_NUMBER;
      hash = (53 * hash) + getNearbyBlocks().hashCode();
    }
    if (hasNearbyItemDrops()) {
      hash = (37 * hash) + NEARBYITEMDROPS_FIELD_NUMBER;
      hash = (53 * hash) + getNearbyItemDrops().hashCode();
    }
    if (hasContainer()) {
      hash = (37 * hash) + CONTAINER_FIELD_NUMBER;
      hash = (53 * hash) + getContainer().hashCode();
    }
    hash = (37 * hash) + CONTAINERTYPE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getContainerType()));
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static me.sand.minecraftaimod.protobuf.State parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static me.sand.minecraftaimod.protobuf.State parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static me.sand.minecraftaimod.protobuf.State parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static me.sand.minecraftaimod.protobuf.State parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static me.sand.minecraftaimod.protobuf.State parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static me.sand.minecraftaimod.protobuf.State parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static me.sand.minecraftaimod.protobuf.State parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static me.sand.minecraftaimod.protobuf.State parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static me.sand.minecraftaimod.protobuf.State parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static me.sand.minecraftaimod.protobuf.State parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static me.sand.minecraftaimod.protobuf.State parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static me.sand.minecraftaimod.protobuf.State parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(me.sand.minecraftaimod.protobuf.State prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code minecraftai.State}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:minecraftai.State)
      me.sand.minecraftaimod.protobuf.StateOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return me.sand.minecraftaimod.protobuf.StateOuterClass.internal_static_minecraftai_State_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return me.sand.minecraftaimod.protobuf.StateOuterClass.internal_static_minecraftai_State_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              me.sand.minecraftaimod.protobuf.State.class, me.sand.minecraftaimod.protobuf.State.Builder.class);
    }

    // Construct using me.sand.minecraftaimod.protobuf.State.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      agentInfo_ = emptyDoubleList();
      inventory_ = null;
      if (inventoryBuilder_ != null) {
        inventoryBuilder_.dispose();
        inventoryBuilder_ = null;
      }
      nearbyEntities_ = null;
      if (nearbyEntitiesBuilder_ != null) {
        nearbyEntitiesBuilder_.dispose();
        nearbyEntitiesBuilder_ = null;
      }
      nearbyBlocks_ = null;
      if (nearbyBlocksBuilder_ != null) {
        nearbyBlocksBuilder_.dispose();
        nearbyBlocksBuilder_ = null;
      }
      nearbyItemDrops_ = null;
      if (nearbyItemDropsBuilder_ != null) {
        nearbyItemDropsBuilder_.dispose();
        nearbyItemDropsBuilder_ = null;
      }
      container_ = null;
      if (containerBuilder_ != null) {
        containerBuilder_.dispose();
        containerBuilder_ = null;
      }
      containerType_ = 0D;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return me.sand.minecraftaimod.protobuf.StateOuterClass.internal_static_minecraftai_State_descriptor;
    }

    @java.lang.Override
    public me.sand.minecraftaimod.protobuf.State getDefaultInstanceForType() {
      return me.sand.minecraftaimod.protobuf.State.getDefaultInstance();
    }

    @java.lang.Override
    public me.sand.minecraftaimod.protobuf.State build() {
      me.sand.minecraftaimod.protobuf.State result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public me.sand.minecraftaimod.protobuf.State buildPartial() {
      me.sand.minecraftaimod.protobuf.State result = new me.sand.minecraftaimod.protobuf.State(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(me.sand.minecraftaimod.protobuf.State result) {
      if (((bitField0_ & 0x00000001) != 0)) {
        agentInfo_.makeImmutable();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.agentInfo_ = agentInfo_;
    }

    private void buildPartial0(me.sand.minecraftaimod.protobuf.State result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.inventory_ = inventoryBuilder_ == null
            ? inventory_
            : inventoryBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.nearbyEntities_ = nearbyEntitiesBuilder_ == null
            ? nearbyEntities_
            : nearbyEntitiesBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.nearbyBlocks_ = nearbyBlocksBuilder_ == null
            ? nearbyBlocks_
            : nearbyBlocksBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.nearbyItemDrops_ = nearbyItemDropsBuilder_ == null
            ? nearbyItemDrops_
            : nearbyItemDropsBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.container_ = containerBuilder_ == null
            ? container_
            : containerBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.containerType_ = containerType_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof me.sand.minecraftaimod.protobuf.State) {
        return mergeFrom((me.sand.minecraftaimod.protobuf.State)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(me.sand.minecraftaimod.protobuf.State other) {
      if (other == me.sand.minecraftaimod.protobuf.State.getDefaultInstance()) return this;
      if (!other.agentInfo_.isEmpty()) {
        if (agentInfo_.isEmpty()) {
          agentInfo_ = other.agentInfo_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureAgentInfoIsMutable();
          agentInfo_.addAll(other.agentInfo_);
        }
        onChanged();
      }
      if (other.hasInventory()) {
        mergeInventory(other.getInventory());
      }
      if (other.hasNearbyEntities()) {
        mergeNearbyEntities(other.getNearbyEntities());
      }
      if (other.hasNearbyBlocks()) {
        mergeNearbyBlocks(other.getNearbyBlocks());
      }
      if (other.hasNearbyItemDrops()) {
        mergeNearbyItemDrops(other.getNearbyItemDrops());
      }
      if (other.hasContainer()) {
        mergeContainer(other.getContainer());
      }
      if (other.getContainerType() != 0D) {
        setContainerType(other.getContainerType());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 9: {
              double v = input.readDouble();
              ensureAgentInfoIsMutable();
              agentInfo_.addDouble(v);
              break;
            } // case 9
            case 10: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              ensureAgentInfoIsMutable();
              while (input.getBytesUntilLimit() > 0) {
                agentInfo_.addDouble(input.readDouble());
              }
              input.popLimit(limit);
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  getInventoryFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              input.readMessage(
                  getNearbyEntitiesFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              input.readMessage(
                  getNearbyBlocksFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              input.readMessage(
                  getNearbyItemDropsFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 50: {
              input.readMessage(
                  getContainerFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            case 57: {
              containerType_ = input.readDouble();
              bitField0_ |= 0x00000040;
              break;
            } // case 57
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.Internal.DoubleList agentInfo_ = emptyDoubleList();
    private void ensureAgentInfoIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        agentInfo_ = mutableCopy(agentInfo_);
        bitField0_ |= 0x00000001;
      }
    }
    /**
     * <code>repeated double agentInfo = 1;</code>
     * @return A list containing the agentInfo.
     */
    public java.util.List<java.lang.Double>
        getAgentInfoList() {
      return ((bitField0_ & 0x00000001) != 0) ?
               java.util.Collections.unmodifiableList(agentInfo_) : agentInfo_;
    }
    /**
     * <code>repeated double agentInfo = 1;</code>
     * @return The count of agentInfo.
     */
    public int getAgentInfoCount() {
      return agentInfo_.size();
    }
    /**
     * <code>repeated double agentInfo = 1;</code>
     * @param index The index of the element to return.
     * @return The agentInfo at the given index.
     */
    public double getAgentInfo(int index) {
      return agentInfo_.getDouble(index);
    }
    /**
     * <code>repeated double agentInfo = 1;</code>
     * @param index The index to set the value at.
     * @param value The agentInfo to set.
     * @return This builder for chaining.
     */
    public Builder setAgentInfo(
        int index, double value) {
      
      ensureAgentInfoIsMutable();
      agentInfo_.setDouble(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated double agentInfo = 1;</code>
     * @param value The agentInfo to add.
     * @return This builder for chaining.
     */
    public Builder addAgentInfo(double value) {
      
      ensureAgentInfoIsMutable();
      agentInfo_.addDouble(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated double agentInfo = 1;</code>
     * @param values The agentInfo to add.
     * @return This builder for chaining.
     */
    public Builder addAllAgentInfo(
        java.lang.Iterable<? extends java.lang.Double> values) {
      ensureAgentInfoIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, agentInfo_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated double agentInfo = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearAgentInfo() {
      agentInfo_ = emptyDoubleList();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }

    private me.sand.minecraftaimod.protobuf.Matrix inventory_;
    private com.google.protobuf.SingleFieldBuilderV3<
        me.sand.minecraftaimod.protobuf.Matrix, me.sand.minecraftaimod.protobuf.Matrix.Builder, me.sand.minecraftaimod.protobuf.MatrixOrBuilder> inventoryBuilder_;
    /**
     * <code>.minecraftai.Matrix inventory = 2;</code>
     * @return Whether the inventory field is set.
     */
    public boolean hasInventory() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>.minecraftai.Matrix inventory = 2;</code>
     * @return The inventory.
     */
    public me.sand.minecraftaimod.protobuf.Matrix getInventory() {
      if (inventoryBuilder_ == null) {
        return inventory_ == null ? me.sand.minecraftaimod.protobuf.Matrix.getDefaultInstance() : inventory_;
      } else {
        return inventoryBuilder_.getMessage();
      }
    }
    /**
     * <code>.minecraftai.Matrix inventory = 2;</code>
     */
    public Builder setInventory(me.sand.minecraftaimod.protobuf.Matrix value) {
      if (inventoryBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        inventory_ = value;
      } else {
        inventoryBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.minecraftai.Matrix inventory = 2;</code>
     */
    public Builder setInventory(
        me.sand.minecraftaimod.protobuf.Matrix.Builder builderForValue) {
      if (inventoryBuilder_ == null) {
        inventory_ = builderForValue.build();
      } else {
        inventoryBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.minecraftai.Matrix inventory = 2;</code>
     */
    public Builder mergeInventory(me.sand.minecraftaimod.protobuf.Matrix value) {
      if (inventoryBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          inventory_ != null &&
          inventory_ != me.sand.minecraftaimod.protobuf.Matrix.getDefaultInstance()) {
          getInventoryBuilder().mergeFrom(value);
        } else {
          inventory_ = value;
        }
      } else {
        inventoryBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.minecraftai.Matrix inventory = 2;</code>
     */
    public Builder clearInventory() {
      bitField0_ = (bitField0_ & ~0x00000002);
      inventory_ = null;
      if (inventoryBuilder_ != null) {
        inventoryBuilder_.dispose();
        inventoryBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.minecraftai.Matrix inventory = 2;</code>
     */
    public me.sand.minecraftaimod.protobuf.Matrix.Builder getInventoryBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getInventoryFieldBuilder().getBuilder();
    }
    /**
     * <code>.minecraftai.Matrix inventory = 2;</code>
     */
    public me.sand.minecraftaimod.protobuf.MatrixOrBuilder getInventoryOrBuilder() {
      if (inventoryBuilder_ != null) {
        return inventoryBuilder_.getMessageOrBuilder();
      } else {
        return inventory_ == null ?
            me.sand.minecraftaimod.protobuf.Matrix.getDefaultInstance() : inventory_;
      }
    }
    /**
     * <code>.minecraftai.Matrix inventory = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        me.sand.minecraftaimod.protobuf.Matrix, me.sand.minecraftaimod.protobuf.Matrix.Builder, me.sand.minecraftaimod.protobuf.MatrixOrBuilder> 
        getInventoryFieldBuilder() {
      if (inventoryBuilder_ == null) {
        inventoryBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            me.sand.minecraftaimod.protobuf.Matrix, me.sand.minecraftaimod.protobuf.Matrix.Builder, me.sand.minecraftaimod.protobuf.MatrixOrBuilder>(
                getInventory(),
                getParentForChildren(),
                isClean());
        inventory_ = null;
      }
      return inventoryBuilder_;
    }

    private me.sand.minecraftaimod.protobuf.Matrix nearbyEntities_;
    private com.google.protobuf.SingleFieldBuilderV3<
        me.sand.minecraftaimod.protobuf.Matrix, me.sand.minecraftaimod.protobuf.Matrix.Builder, me.sand.minecraftaimod.protobuf.MatrixOrBuilder> nearbyEntitiesBuilder_;
    /**
     * <code>.minecraftai.Matrix nearbyEntities = 3;</code>
     * @return Whether the nearbyEntities field is set.
     */
    public boolean hasNearbyEntities() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>.minecraftai.Matrix nearbyEntities = 3;</code>
     * @return The nearbyEntities.
     */
    public me.sand.minecraftaimod.protobuf.Matrix getNearbyEntities() {
      if (nearbyEntitiesBuilder_ == null) {
        return nearbyEntities_ == null ? me.sand.minecraftaimod.protobuf.Matrix.getDefaultInstance() : nearbyEntities_;
      } else {
        return nearbyEntitiesBuilder_.getMessage();
      }
    }
    /**
     * <code>.minecraftai.Matrix nearbyEntities = 3;</code>
     */
    public Builder setNearbyEntities(me.sand.minecraftaimod.protobuf.Matrix value) {
      if (nearbyEntitiesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        nearbyEntities_ = value;
      } else {
        nearbyEntitiesBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.minecraftai.Matrix nearbyEntities = 3;</code>
     */
    public Builder setNearbyEntities(
        me.sand.minecraftaimod.protobuf.Matrix.Builder builderForValue) {
      if (nearbyEntitiesBuilder_ == null) {
        nearbyEntities_ = builderForValue.build();
      } else {
        nearbyEntitiesBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.minecraftai.Matrix nearbyEntities = 3;</code>
     */
    public Builder mergeNearbyEntities(me.sand.minecraftaimod.protobuf.Matrix value) {
      if (nearbyEntitiesBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0) &&
          nearbyEntities_ != null &&
          nearbyEntities_ != me.sand.minecraftaimod.protobuf.Matrix.getDefaultInstance()) {
          getNearbyEntitiesBuilder().mergeFrom(value);
        } else {
          nearbyEntities_ = value;
        }
      } else {
        nearbyEntitiesBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.minecraftai.Matrix nearbyEntities = 3;</code>
     */
    public Builder clearNearbyEntities() {
      bitField0_ = (bitField0_ & ~0x00000004);
      nearbyEntities_ = null;
      if (nearbyEntitiesBuilder_ != null) {
        nearbyEntitiesBuilder_.dispose();
        nearbyEntitiesBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.minecraftai.Matrix nearbyEntities = 3;</code>
     */
    public me.sand.minecraftaimod.protobuf.Matrix.Builder getNearbyEntitiesBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return getNearbyEntitiesFieldBuilder().getBuilder();
    }
    /**
     * <code>.minecraftai.Matrix nearbyEntities = 3;</code>
     */
    public me.sand.minecraftaimod.protobuf.MatrixOrBuilder getNearbyEntitiesOrBuilder() {
      if (nearbyEntitiesBuilder_ != null) {
        return nearbyEntitiesBuilder_.getMessageOrBuilder();
      } else {
        return nearbyEntities_ == null ?
            me.sand.minecraftaimod.protobuf.Matrix.getDefaultInstance() : nearbyEntities_;
      }
    }
    /**
     * <code>.minecraftai.Matrix nearbyEntities = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        me.sand.minecraftaimod.protobuf.Matrix, me.sand.minecraftaimod.protobuf.Matrix.Builder, me.sand.minecraftaimod.protobuf.MatrixOrBuilder> 
        getNearbyEntitiesFieldBuilder() {
      if (nearbyEntitiesBuilder_ == null) {
        nearbyEntitiesBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            me.sand.minecraftaimod.protobuf.Matrix, me.sand.minecraftaimod.protobuf.Matrix.Builder, me.sand.minecraftaimod.protobuf.MatrixOrBuilder>(
                getNearbyEntities(),
                getParentForChildren(),
                isClean());
        nearbyEntities_ = null;
      }
      return nearbyEntitiesBuilder_;
    }

    private me.sand.minecraftaimod.protobuf.Matrix3D nearbyBlocks_;
    private com.google.protobuf.SingleFieldBuilderV3<
        me.sand.minecraftaimod.protobuf.Matrix3D, me.sand.minecraftaimod.protobuf.Matrix3D.Builder, me.sand.minecraftaimod.protobuf.Matrix3DOrBuilder> nearbyBlocksBuilder_;
    /**
     * <code>.minecraftai.Matrix3D nearbyBlocks = 4;</code>
     * @return Whether the nearbyBlocks field is set.
     */
    public boolean hasNearbyBlocks() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>.minecraftai.Matrix3D nearbyBlocks = 4;</code>
     * @return The nearbyBlocks.
     */
    public me.sand.minecraftaimod.protobuf.Matrix3D getNearbyBlocks() {
      if (nearbyBlocksBuilder_ == null) {
        return nearbyBlocks_ == null ? me.sand.minecraftaimod.protobuf.Matrix3D.getDefaultInstance() : nearbyBlocks_;
      } else {
        return nearbyBlocksBuilder_.getMessage();
      }
    }
    /**
     * <code>.minecraftai.Matrix3D nearbyBlocks = 4;</code>
     */
    public Builder setNearbyBlocks(me.sand.minecraftaimod.protobuf.Matrix3D value) {
      if (nearbyBlocksBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        nearbyBlocks_ = value;
      } else {
        nearbyBlocksBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>.minecraftai.Matrix3D nearbyBlocks = 4;</code>
     */
    public Builder setNearbyBlocks(
        me.sand.minecraftaimod.protobuf.Matrix3D.Builder builderForValue) {
      if (nearbyBlocksBuilder_ == null) {
        nearbyBlocks_ = builderForValue.build();
      } else {
        nearbyBlocksBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>.minecraftai.Matrix3D nearbyBlocks = 4;</code>
     */
    public Builder mergeNearbyBlocks(me.sand.minecraftaimod.protobuf.Matrix3D value) {
      if (nearbyBlocksBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0) &&
          nearbyBlocks_ != null &&
          nearbyBlocks_ != me.sand.minecraftaimod.protobuf.Matrix3D.getDefaultInstance()) {
          getNearbyBlocksBuilder().mergeFrom(value);
        } else {
          nearbyBlocks_ = value;
        }
      } else {
        nearbyBlocksBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>.minecraftai.Matrix3D nearbyBlocks = 4;</code>
     */
    public Builder clearNearbyBlocks() {
      bitField0_ = (bitField0_ & ~0x00000008);
      nearbyBlocks_ = null;
      if (nearbyBlocksBuilder_ != null) {
        nearbyBlocksBuilder_.dispose();
        nearbyBlocksBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.minecraftai.Matrix3D nearbyBlocks = 4;</code>
     */
    public me.sand.minecraftaimod.protobuf.Matrix3D.Builder getNearbyBlocksBuilder() {
      bitField0_ |= 0x00000008;
      onChanged();
      return getNearbyBlocksFieldBuilder().getBuilder();
    }
    /**
     * <code>.minecraftai.Matrix3D nearbyBlocks = 4;</code>
     */
    public me.sand.minecraftaimod.protobuf.Matrix3DOrBuilder getNearbyBlocksOrBuilder() {
      if (nearbyBlocksBuilder_ != null) {
        return nearbyBlocksBuilder_.getMessageOrBuilder();
      } else {
        return nearbyBlocks_ == null ?
            me.sand.minecraftaimod.protobuf.Matrix3D.getDefaultInstance() : nearbyBlocks_;
      }
    }
    /**
     * <code>.minecraftai.Matrix3D nearbyBlocks = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        me.sand.minecraftaimod.protobuf.Matrix3D, me.sand.minecraftaimod.protobuf.Matrix3D.Builder, me.sand.minecraftaimod.protobuf.Matrix3DOrBuilder> 
        getNearbyBlocksFieldBuilder() {
      if (nearbyBlocksBuilder_ == null) {
        nearbyBlocksBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            me.sand.minecraftaimod.protobuf.Matrix3D, me.sand.minecraftaimod.protobuf.Matrix3D.Builder, me.sand.minecraftaimod.protobuf.Matrix3DOrBuilder>(
                getNearbyBlocks(),
                getParentForChildren(),
                isClean());
        nearbyBlocks_ = null;
      }
      return nearbyBlocksBuilder_;
    }

    private me.sand.minecraftaimod.protobuf.Matrix4D nearbyItemDrops_;
    private com.google.protobuf.SingleFieldBuilderV3<
        me.sand.minecraftaimod.protobuf.Matrix4D, me.sand.minecraftaimod.protobuf.Matrix4D.Builder, me.sand.minecraftaimod.protobuf.Matrix4DOrBuilder> nearbyItemDropsBuilder_;
    /**
     * <code>.minecraftai.Matrix4D nearbyItemDrops = 5;</code>
     * @return Whether the nearbyItemDrops field is set.
     */
    public boolean hasNearbyItemDrops() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>.minecraftai.Matrix4D nearbyItemDrops = 5;</code>
     * @return The nearbyItemDrops.
     */
    public me.sand.minecraftaimod.protobuf.Matrix4D getNearbyItemDrops() {
      if (nearbyItemDropsBuilder_ == null) {
        return nearbyItemDrops_ == null ? me.sand.minecraftaimod.protobuf.Matrix4D.getDefaultInstance() : nearbyItemDrops_;
      } else {
        return nearbyItemDropsBuilder_.getMessage();
      }
    }
    /**
     * <code>.minecraftai.Matrix4D nearbyItemDrops = 5;</code>
     */
    public Builder setNearbyItemDrops(me.sand.minecraftaimod.protobuf.Matrix4D value) {
      if (nearbyItemDropsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        nearbyItemDrops_ = value;
      } else {
        nearbyItemDropsBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>.minecraftai.Matrix4D nearbyItemDrops = 5;</code>
     */
    public Builder setNearbyItemDrops(
        me.sand.minecraftaimod.protobuf.Matrix4D.Builder builderForValue) {
      if (nearbyItemDropsBuilder_ == null) {
        nearbyItemDrops_ = builderForValue.build();
      } else {
        nearbyItemDropsBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>.minecraftai.Matrix4D nearbyItemDrops = 5;</code>
     */
    public Builder mergeNearbyItemDrops(me.sand.minecraftaimod.protobuf.Matrix4D value) {
      if (nearbyItemDropsBuilder_ == null) {
        if (((bitField0_ & 0x00000010) != 0) &&
          nearbyItemDrops_ != null &&
          nearbyItemDrops_ != me.sand.minecraftaimod.protobuf.Matrix4D.getDefaultInstance()) {
          getNearbyItemDropsBuilder().mergeFrom(value);
        } else {
          nearbyItemDrops_ = value;
        }
      } else {
        nearbyItemDropsBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>.minecraftai.Matrix4D nearbyItemDrops = 5;</code>
     */
    public Builder clearNearbyItemDrops() {
      bitField0_ = (bitField0_ & ~0x00000010);
      nearbyItemDrops_ = null;
      if (nearbyItemDropsBuilder_ != null) {
        nearbyItemDropsBuilder_.dispose();
        nearbyItemDropsBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.minecraftai.Matrix4D nearbyItemDrops = 5;</code>
     */
    public me.sand.minecraftaimod.protobuf.Matrix4D.Builder getNearbyItemDropsBuilder() {
      bitField0_ |= 0x00000010;
      onChanged();
      return getNearbyItemDropsFieldBuilder().getBuilder();
    }
    /**
     * <code>.minecraftai.Matrix4D nearbyItemDrops = 5;</code>
     */
    public me.sand.minecraftaimod.protobuf.Matrix4DOrBuilder getNearbyItemDropsOrBuilder() {
      if (nearbyItemDropsBuilder_ != null) {
        return nearbyItemDropsBuilder_.getMessageOrBuilder();
      } else {
        return nearbyItemDrops_ == null ?
            me.sand.minecraftaimod.protobuf.Matrix4D.getDefaultInstance() : nearbyItemDrops_;
      }
    }
    /**
     * <code>.minecraftai.Matrix4D nearbyItemDrops = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        me.sand.minecraftaimod.protobuf.Matrix4D, me.sand.minecraftaimod.protobuf.Matrix4D.Builder, me.sand.minecraftaimod.protobuf.Matrix4DOrBuilder> 
        getNearbyItemDropsFieldBuilder() {
      if (nearbyItemDropsBuilder_ == null) {
        nearbyItemDropsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            me.sand.minecraftaimod.protobuf.Matrix4D, me.sand.minecraftaimod.protobuf.Matrix4D.Builder, me.sand.minecraftaimod.protobuf.Matrix4DOrBuilder>(
                getNearbyItemDrops(),
                getParentForChildren(),
                isClean());
        nearbyItemDrops_ = null;
      }
      return nearbyItemDropsBuilder_;
    }

    private me.sand.minecraftaimod.protobuf.Matrix container_;
    private com.google.protobuf.SingleFieldBuilderV3<
        me.sand.minecraftaimod.protobuf.Matrix, me.sand.minecraftaimod.protobuf.Matrix.Builder, me.sand.minecraftaimod.protobuf.MatrixOrBuilder> containerBuilder_;
    /**
     * <code>.minecraftai.Matrix container = 6;</code>
     * @return Whether the container field is set.
     */
    public boolean hasContainer() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>.minecraftai.Matrix container = 6;</code>
     * @return The container.
     */
    public me.sand.minecraftaimod.protobuf.Matrix getContainer() {
      if (containerBuilder_ == null) {
        return container_ == null ? me.sand.minecraftaimod.protobuf.Matrix.getDefaultInstance() : container_;
      } else {
        return containerBuilder_.getMessage();
      }
    }
    /**
     * <code>.minecraftai.Matrix container = 6;</code>
     */
    public Builder setContainer(me.sand.minecraftaimod.protobuf.Matrix value) {
      if (containerBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        container_ = value;
      } else {
        containerBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>.minecraftai.Matrix container = 6;</code>
     */
    public Builder setContainer(
        me.sand.minecraftaimod.protobuf.Matrix.Builder builderForValue) {
      if (containerBuilder_ == null) {
        container_ = builderForValue.build();
      } else {
        containerBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>.minecraftai.Matrix container = 6;</code>
     */
    public Builder mergeContainer(me.sand.minecraftaimod.protobuf.Matrix value) {
      if (containerBuilder_ == null) {
        if (((bitField0_ & 0x00000020) != 0) &&
          container_ != null &&
          container_ != me.sand.minecraftaimod.protobuf.Matrix.getDefaultInstance()) {
          getContainerBuilder().mergeFrom(value);
        } else {
          container_ = value;
        }
      } else {
        containerBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>.minecraftai.Matrix container = 6;</code>
     */
    public Builder clearContainer() {
      bitField0_ = (bitField0_ & ~0x00000020);
      container_ = null;
      if (containerBuilder_ != null) {
        containerBuilder_.dispose();
        containerBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.minecraftai.Matrix container = 6;</code>
     */
    public me.sand.minecraftaimod.protobuf.Matrix.Builder getContainerBuilder() {
      bitField0_ |= 0x00000020;
      onChanged();
      return getContainerFieldBuilder().getBuilder();
    }
    /**
     * <code>.minecraftai.Matrix container = 6;</code>
     */
    public me.sand.minecraftaimod.protobuf.MatrixOrBuilder getContainerOrBuilder() {
      if (containerBuilder_ != null) {
        return containerBuilder_.getMessageOrBuilder();
      } else {
        return container_ == null ?
            me.sand.minecraftaimod.protobuf.Matrix.getDefaultInstance() : container_;
      }
    }
    /**
     * <code>.minecraftai.Matrix container = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        me.sand.minecraftaimod.protobuf.Matrix, me.sand.minecraftaimod.protobuf.Matrix.Builder, me.sand.minecraftaimod.protobuf.MatrixOrBuilder> 
        getContainerFieldBuilder() {
      if (containerBuilder_ == null) {
        containerBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            me.sand.minecraftaimod.protobuf.Matrix, me.sand.minecraftaimod.protobuf.Matrix.Builder, me.sand.minecraftaimod.protobuf.MatrixOrBuilder>(
                getContainer(),
                getParentForChildren(),
                isClean());
        container_ = null;
      }
      return containerBuilder_;
    }

    private double containerType_ ;
    /**
     * <code>double containerType = 7;</code>
     * @return The containerType.
     */
    @java.lang.Override
    public double getContainerType() {
      return containerType_;
    }
    /**
     * <code>double containerType = 7;</code>
     * @param value The containerType to set.
     * @return This builder for chaining.
     */
    public Builder setContainerType(double value) {
      
      containerType_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>double containerType = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearContainerType() {
      bitField0_ = (bitField0_ & ~0x00000040);
      containerType_ = 0D;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:minecraftai.State)
  }

  // @@protoc_insertion_point(class_scope:minecraftai.State)
  private static final me.sand.minecraftaimod.protobuf.State DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new me.sand.minecraftaimod.protobuf.State();
  }

  public static me.sand.minecraftaimod.protobuf.State getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<State>
      PARSER = new com.google.protobuf.AbstractParser<State>() {
    @java.lang.Override
    public State parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<State> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<State> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public me.sand.minecraftaimod.protobuf.State getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

