// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: state.proto

package me.sand.minecraftaimod.protobuf;

public final class StateOuterClass {
  private StateOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_minecraftai_Matrix3D_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_minecraftai_Matrix3D_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_minecraftai_Matrix4D_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_minecraftai_Matrix4D_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_minecraftai_Matrix_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_minecraftai_Matrix_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_minecraftai_Row_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_minecraftai_Row_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_minecraftai_State_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_minecraftai_State_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_minecraftai_Action_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_minecraftai_Action_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013state.proto\022\013minecraftai\"/\n\010Matrix3D\022#" +
      "\n\006matrix\030\001 \003(\0132\023.minecraftai.Matrix\"3\n\010M" +
      "atrix4D\022\'\n\010matrix3D\030\001 \003(\0132\025.minecraftai." +
      "Matrix3D\"(\n\006Matrix\022\036\n\004rows\030\001 \003(\0132\020.minec" +
      "raftai.Row\"\025\n\003Row\022\016\n\006values\030\001 \003(\001\"\213\002\n\005St" +
      "ate\022\021\n\tagentInfo\030\001 \003(\001\022&\n\tinventory\030\002 \001(" +
      "\0132\023.minecraftai.Matrix\022+\n\016nearbyEntities" +
      "\030\003 \001(\0132\023.minecraftai.Matrix\022+\n\014nearbyBlo" +
      "cks\030\004 \001(\0132\025.minecraftai.Matrix3D\022.\n\017near" +
      "byItemDrops\030\005 \001(\0132\025.minecraftai.Matrix4D" +
      "\022&\n\tcontainer\030\006 \001(\0132\023.minecraftai.Matrix" +
      "\022\025\n\rcontainerType\030\007 \001(\001\"\031\n\006Action\022\017\n\007act" +
      "ions\030\001 \003(\002B#\n\037me.sand.minecraftaimod.pro" +
      "tobufP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_minecraftai_Matrix3D_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_minecraftai_Matrix3D_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_minecraftai_Matrix3D_descriptor,
        new java.lang.String[] { "Matrix", });
    internal_static_minecraftai_Matrix4D_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_minecraftai_Matrix4D_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_minecraftai_Matrix4D_descriptor,
        new java.lang.String[] { "Matrix3D", });
    internal_static_minecraftai_Matrix_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_minecraftai_Matrix_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_minecraftai_Matrix_descriptor,
        new java.lang.String[] { "Rows", });
    internal_static_minecraftai_Row_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_minecraftai_Row_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_minecraftai_Row_descriptor,
        new java.lang.String[] { "Values", });
    internal_static_minecraftai_State_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_minecraftai_State_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_minecraftai_State_descriptor,
        new java.lang.String[] { "AgentInfo", "Inventory", "NearbyEntities", "NearbyBlocks", "NearbyItemDrops", "Container", "ContainerType", });
    internal_static_minecraftai_Action_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_minecraftai_Action_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_minecraftai_Action_descriptor,
        new java.lang.String[] { "Actions", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
